language: node_js
node_js: 
    - '11'
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "592837154"
  - git config user.email "592837154@qq.com"
  - git add -A
  - git commit -m "Update documents"
  - git push --force  "https://${TOCKEN}@https://github.com/592837154/ts-hexo.git" "master:gh-pages"
branches:
  only:
    - master